# Generated by Django 2.1.4 on 2019-06-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0007_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='viewsCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='ServiceCore.JobOffer'),
        ),
    ]
