# Generated by Django 2.1.4 on 2019-06-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0008_auto_20190615_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='viewsCount',
            field=models.IntegerField(default=0),
        ),
    ]
