# Generated by Django 2.2.1 on 2019-06-16 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0009_auto_20190615_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='companyLoacation',
            field=models.CharField(default='DefaultLocation', max_length=128),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='companyName',
            field=models.CharField(default='DefaultCompany', max_length=128),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='dateofpost',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='numberOfAplications',
            field=models.IntegerField(default=0),
        ),
    ]
